///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PlattformTests.Playground
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ChangeAge recording.
    /// </summary>
    [TestModule("e2b82516-6b53-4043-bed6-e639e77e4618", ModuleType.Recording, 1)]
    public partial class ChangeAge : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PlattformTests.PlatformTestsRepository repository.
        /// </summary>
        public static PlattformTests.PlatformTestsRepository repo = PlattformTests.PlatformTestsRepository.Instance;

        static ChangeAge instance = new ChangeAge();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ChangeAge()
        {
            ChildrenAge = "10";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ChangeAge Instance
        {
            get { return instance; }
        }

#region Variables

        string _ChildrenAge;

        /// <summary>
        /// Gets or sets the value of variable ChildrenAge.
        /// </summary>
        [TestVariable("7d9bf65c-02a0-472d-a5a6-9bed9b6346eb")]
        public string ChildrenAge
        {
            get { return _ChildrenAge; }
            set { _ChildrenAge = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Middle DoubleClick item 'PKSimR51.LayoutControl.TextMaskBox' at 40;10.", repo.PKSimR51.LayoutControl.TextMaskBoxInfo, new RecordItemIndex(0));
            repo.PKSimR51.LayoutControl.TextMaskBox.DoubleClick(System.Windows.Forms.MouseButtons.Middle, "40;10");
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Back' Down with focus on 'PKSimR51.LayoutControl.TextMaskBox'.", repo.PKSimR51.LayoutControl.TextMaskBoxInfo, new RecordItemIndex(1));
            Keyboard.PrepareFocus(repo.PKSimR51.LayoutControl.TextMaskBox);
            Keyboard.Down(System.Windows.Forms.Keys.Back, 14, false);
            Delay.Milliseconds(500);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Back' Down with focus on 'PKSimR51.LayoutControl.TextMaskBox'.", repo.PKSimR51.LayoutControl.TextMaskBoxInfo, new RecordItemIndex(2));
            Keyboard.PrepareFocus(repo.PKSimR51.LayoutControl.TextMaskBox);
            Keyboard.Down(System.Windows.Forms.Keys.Back, 14, false);
            Delay.Milliseconds(40);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Back' Down with focus on 'PKSimR51.LayoutControl.TextMaskBox'.", repo.PKSimR51.LayoutControl.TextMaskBoxInfo, new RecordItemIndex(3));
            Keyboard.PrepareFocus(repo.PKSimR51.LayoutControl.TextMaskBox);
            Keyboard.Down(System.Windows.Forms.Keys.Back, 14, false);
            Delay.Milliseconds(30);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Back' Down with focus on 'PKSimR51.LayoutControl.TextMaskBox'.", repo.PKSimR51.LayoutControl.TextMaskBoxInfo, new RecordItemIndex(4));
            Keyboard.PrepareFocus(repo.PKSimR51.LayoutControl.TextMaskBox);
            Keyboard.Down(System.Windows.Forms.Keys.Back, 14, false);
            Delay.Milliseconds(30);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ChildrenAge' with focus on 'PKSimR51.LayoutControl.TextMaskBox'.", repo.PKSimR51.LayoutControl.TextMaskBoxInfo, new RecordItemIndex(5));
            repo.PKSimR51.LayoutControl.TextMaskBox.PressKeys(ChildrenAge);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
