///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PlattformTests.Playground
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The setParameter recording.
    /// </summary>
    [TestModule("57a37d78-c451-4d0e-bb84-81924498464a", ModuleType.Recording, 1)]
    public partial class setParameter : ITestModule
    {
        /// <summary>
        /// Holds an instance of the PlattformTests.PlatformTestsRepository repository.
        /// </summary>
        public static PlattformTests.PlatformTestsRepository repo = PlattformTests.PlatformTestsRepository.Instance;

        static setParameter instance = new setParameter();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public setParameter()
        {
            ParameterValue = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static setParameter Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable ParameterValue.
        /// </summary>
        [TestVariable("4e24db67-9bac-4fd0-b694-396437356f32")]
        public string ParameterValue
        {
            get { return repo.parameterValue; }
            set { repo.parameterValue = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.0")]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left DoubleClick item 'PKSimR51.LayoutControl.TextMaskBox' at Center.", repo.PKSimR51.LayoutControl.TextMaskBoxInfo, new RecordItemIndex(0));
            repo.PKSimR51.LayoutControl.TextMaskBox.DoubleClick();
            Delay.Milliseconds(200);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ParameterValue' with focus on 'PKSimR51.LayoutControl.TextMaskBox'.", repo.PKSimR51.LayoutControl.TextMaskBoxInfo, new RecordItemIndex(1));
            repo.PKSimR51.LayoutControl.TextMaskBox.PressKeys(ParameterValue);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
